AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket with environment tagging'

Parameters:
  Environment:
    Type: String
    Default: Test
    AllowedValues:
      - Test
      - Staging
      - Production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionsDemo

Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'
    Value: !Ref MyS3Bucket
